import pandas as pd
import pyodbc
import streamlit as st
import plotly.express as px
import locale
from io import BytesIO


import datetime
import pickle 
import os
CACHE_FILE = "cache.pkl"
class DataBase:
    def __init__(self,dbon,dvg,ddep,cmv):
        self.timeCreated = datetime.datetime.now()
        self.consultaDbon = dbon
        self.consultaDvg = dvg
        self.consultaDdep = ddep
        self.consultaCmv = cmv

def save_to_cache(obj):
    """Salva o objeto no arquivo usando pickle."""
    with open(CACHE_FILE, "wb") as f:
        pickle.dump(obj, f)

def load_from_cache():
    """Carrega o objeto do arquivo, se existir e for válido."""
    if os.path.exists(CACHE_FILE):
        with open(CACHE_FILE, "rb") as f:
            obj = pickle.load(f)

        # Verifica se o objeto foi criado hoje
        obj_date = datetime.fromisoformat(obj.date_created).date()
        if obj_date == datetime.now().date():
            return obj  # Retorna o objeto se for do mesmo dia

    return None  # Retorna None se não houver um cache válido

def get_cached_object():
    """Retorna o objeto do cache ou cria um novo se necessário."""
    obj = load_from_cache()
    if obj is None:
        locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
        conn_str = (
            "DRIVER={SQL Server};"
            "SERVER=LMPBDL02\\LM_QA;"
            "DATABASE=DADOSMP11;"
            "Trusted_Connection=yes;"
        )

        conn = pyodbc.connect(conn_str)

        qbon = """
        SELECT DISTINCT
        'LM' AS UNIDADE,
        RTRIM(A2_NREDUZ) AS MARCA,
        B1_YFINALI,
        F1_EMISSAO AS EMISSAO,
        F1_DOC,
        F1_FORNECE,
        F1_VALBRUT,
        F1_CHVNFE

        FROM SF1020

        JOIN SD1020 ON D1_DOC = F1_DOC AND D1_FILIAL = F1_FILIAL AND D1_SERIE = F1_SERIE
        JOIN SA2020 ON F1_FORNECE = A2_COD AND A2_LOJA = F1_LOJA
        JOIN SB1020 ON D1_COD = B1_COD AND B1_FILIAL = D1_FILIAL

        WHERE 
        D1_CF IN ('2910', '1910')
        AND A2_YPZENT <> ''
        AND B1_YFINALI = '1'
        AND D1_EMISSAO >= '20241201'

        UNION ALL 


        SELECT DISTINCT
        'MB' AS UNIDADE,
        RTRIM(A2_NREDUZ) AS MARCA,
        B1_YFINALI,
        F1_EMISSAO AS EMISSAO,
        F1_DOC,
        F1_FORNECE,
        F1_VALBRUT,
        F1_CHVNFE

        FROM SF1010

        JOIN SD1010 ON D1_DOC = F1_DOC AND D1_FILIAL = F1_FILIAL AND D1_SERIE = F1_SERIE
        JOIN SA2010 ON F1_FORNECE = A2_COD AND A2_LOJA = F1_LOJA
        JOIN SB1010 ON D1_COD = B1_COD AND B1_FILIAL = D1_FILIAL

        WHERE 
        D1_CF IN ('2910', '1910')
        AND A2_YPZENT <> ''
        AND B1_YFINALI = '1'
        AND D1_EMISSAO >= '20241201'
        AND F1_FILIAL = '02'

        UNION ALL 


        SELECT DISTINCT
        'WCO' AS UNIDADE,
        RTRIM(A2_NREDUZ) AS MARCA,
        B1_YFINALI,
        F1_EMISSAO AS EMISSAO,
        F1_DOC,
        F1_FORNECE,
        F1_VALBRUT,
        F1_CHVNFE

        FROM SF1040

        JOIN SD1040 ON D1_DOC = F1_DOC AND D1_FILIAL = F1_FILIAL AND D1_SERIE = F1_SERIE
        JOIN SA2040 ON F1_FORNECE = A2_COD AND A2_LOJA = F1_LOJA
        JOIN SB1040 ON D1_COD = B1_COD AND B1_FILIAL = D1_FILIAL

        WHERE 
        D1_CF IN ('2910', '1910')
        AND A2_YPZENT <> ''
        AND B1_YFINALI = '1'
        AND D1_EMISSAO >= '20241201'

        UNION ALL 


        SELECT DISTINCT
        'WSP' AS UNIDADE,
        RTRIM(A2_NREDUZ) AS MARCA,
        B1_YFINALI,
        F1_EMISSAO AS EMISSAO,
        F1_DOC,
        F1_FORNECE,
        F1_VALBRUT,
        F1_CHVNFE

        FROM SF1050

        JOIN SD1050 ON D1_DOC = F1_DOC AND D1_FILIAL = F1_FILIAL AND D1_SERIE = F1_SERIE
        JOIN SA2050 ON F1_FORNECE = A2_COD AND A2_LOJA = F1_LOJA
        JOIN SB1050 ON D1_COD = B1_COD AND B1_FILIAL = D1_FILIAL

        WHERE 
        D1_CF IN ('2910', '1910')
        AND A2_YPZENT <> ''
        AND B1_YFINALI = '1'
        AND F1_EMISSAO >= '20241201'

        UNION ALL 


        SELECT DISTINCT
        'WSUL' AS UNIDADE,
        RTRIM(A2_NREDUZ) AS MARCA,
        B1_YFINALI,
        F1_EMISSAO AS EMISSAO,
        F1_DOC,
        F1_FORNECE,
        F1_VALBRUT,
        F1_CHVNFE

        FROM SF1080

        JOIN SD1080 ON D1_DOC = F1_DOC AND D1_FILIAL = F1_FILIAL AND D1_SERIE = F1_SERIE
        JOIN SA2080 ON F1_FORNECE = A2_COD AND A2_LOJA = F1_LOJA
        JOIN SB1080 ON D1_COD = B1_COD AND B1_FILIAL = D1_FILIAL

        WHERE 
        D1_CF IN ('2910', '1910')
        AND A2_YPZENT <> ''
        AND B1_YFINALI = '1'
        AND D1_EMISSAO >= '20241201'

        UNION ALL 


        SELECT DISTINCT
        CONCAT('WNE_', F1_FILIAL) AS UNIDADE,
        RTRIM(A2_NREDUZ) AS MARCA,
        B1_YFINALI,
        F1_EMISSAO AS EMISSAO,
        F1_DOC,
        F1_FORNECE,
        F1_VALBRUT,
        F1_CHVNFE

        FROM SF1090

        JOIN SD1090 ON D1_DOC = F1_DOC AND D1_FILIAL = F1_FILIAL AND D1_SERIE = F1_SERIE
        JOIN SA2090 ON F1_FORNECE = A2_COD AND A2_LOJA = F1_LOJA
        JOIN SB1090 ON D1_COD = B1_COD AND B1_FILIAL = D1_FILIAL

        WHERE 
        D1_CF IN ('2910', '1910')
        AND A2_YPZENT <> ''
        AND B1_YFINALI = '1'
        AND D1_EMISSAO >= '20241201'

        UNION ALL 


        SELECT DISTINCT
        'WMG_03' AS UNIDADE,
        RTRIM(A2_NREDUZ) AS MARCA,
        B1_YFINALI,
        F1_EMISSAO AS EMISSAO,
        F1_DOC,
        F1_FORNECE,
        F1_VALBRUT,
        F1_CHVNFE

        FROM SF1300

        JOIN SD1300 ON D1_DOC = F1_DOC AND D1_FILIAL = F1_FILIAL AND D1_SERIE = F1_SERIE
        JOIN SA2300 ON F1_FORNECE = A2_COD AND A2_LOJA = F1_LOJA
        JOIN SB1300 ON D1_COD = B1_COD AND B1_FILIAL = D1_FILIAL

        WHERE 
        D1_CF IN ('2910', '1910')
        AND A2_YPZENT <> ''
        AND B1_YFINALI = '1'
        AND D1_EMISSAO >= '20241201'

        """

        qcmv = """
        SELECT 
        Marca AS MARCA,
        LEFT(DtFaturamento,4) AS ANO,
        RIGHT(LEFT(DtFaturamento,6),2) AS MES,
        SUM(VlrBruto) AS ROB,
        SUM(CustoContabil) AS CUSTO,
        SUM(CustoContabil) / SUM(VlrBruto) AS CMV

        FROM  DADOS_BI.dbo.tb_ExpFatGeral WITH (NOLOCK)

        WHERE 
        AnoComercial IN ('2025')
            AND Finalidade IN ('MOTO')
        AND BCI IN ('MOTO')
        AND DescTipGrp IN ('NACIONAL','PNEUMATICO NAC')


        GROUP BY
        Marca,
        LEFT(DtFaturamento,4),
        RIGHT(LEFT(DtFaturamento,6),2)
        """

        qdep = """
        SELECT 
        CONCAT('LM',E2_FILIAL) AS UNIDADE
        ,E2_EMISSAO AS EMISSAO
        ,E2_NUM AS TITULO
        ,ISNULL (D2_NFORI,'')AS NF_COMPRA
        ,E2_PREFIXO AS PREFIXO
        ,E2_TIPO AS TIPO
        ,E2_NATUREZ AS NATUREZA
        ,ED_DESCRIC AS DESC_NATUREZA
        ,RTRIM(A2_NREDUZ) AS MARCA
        ,E2_VALOR AS VL_TOTAL
        ,E2_SALDO AS VL_SALDO
        ,RTRIM(LTRIM(E2_HIST)) AS E2_HIST

        FROM SE2020 SE2 WITH (NOLOCK)

        INNER JOIN SA2020 SA2 WITH (NOLOCK) ON SA2.D_E_L_E_T_='' AND A2_COD=E2_FORNECE AND A2_LOJA=E2_LOJA 
        LEFT JOIN SED020 SED WITH (NOLOCK) ON SED.D_E_L_E_T_='' AND ED_CODIGO=E2_NATUREZ
        LEFT JOIN SY1000 SY1 WITH (NOLOCK) ON SY1.D_E_L_E_T_='' AND Y1_USER= REPLACE((SUBSTRING(E2_USERLGI, 3, 1)+SUBSTRING(E2_USERLGI, 7, 1)+
        SUBSTRING(E2_USERLGI, 11,1)+SUBSTRING(E2_USERLGI, 15,1)+
        SUBSTRING(E2_USERLGI, 2, 1)+SUBSTRING(E2_USERLGI, 6, 1)+
        SUBSTRING(E2_USERLGI, 10,1)+SUBSTRING(E2_USERLGI, 14,1)+
        SUBSTRING(E2_USERLGI, 1, 1)+SUBSTRING(E2_USERLGI, 5, 1)+
        SUBSTRING(E2_USERLGI, 9, 1)+SUBSTRING(E2_USERLGI, 13,1)+
        SUBSTRING(E2_USERLGI, 17,1)+SUBSTRING(E2_USERLGI, 4, 1)+
        SUBSTRING(E2_USERLGI, 8, 1)),'#@','')
        LEFT JOIN (			SELECT D2_FILIAL,D2_DOC,D2_NFORI
                            FROM SD2020 SD2
                            WHERE SD2.D_E_L_E_T_='' AND D2_NFORI<>''
                            GROUP BY D2_FILIAL,D2_DOC,D2_NFORI) COMPRA ON D2_FILIAL=E2_FILIAL AND D2_DOC=E2_NUM

        WHERE SE2.D_E_L_E_T_='' 
        AND E2_FILIAL = '02'
        --AND E2_SALDO<>'0' 
        AND E2_USUALIB NOT IN ('BLOQ.WIS','LIB.WIS')
        AND E2_TIPO = 'NDF'
        AND D2_NFORI IS NULL 
        AND A2_YPZENT <> ''
        AND E2_EMISSAO > '20250101'
        AND E2_PREFIXO <> ''

        UNION ALL

        SELECT 
        CONCAT('MB',E2_FILIAL) AS UNIDADE
        ,E2_EMISSAO AS EMISSAO
        ,E2_NUM AS TITULO
        ,ISNULL (D2_NFORI,'')AS NF_COMPRA
        ,E2_PREFIXO AS PREFIXO
        ,E2_TIPO AS TIPO
        ,E2_NATUREZ AS NATUREZA
        ,ED_DESCRIC AS DESC_NATUREZA
        ,RTRIM(A2_NREDUZ) AS MARCA
        ,E2_VALOR AS VL_TOTAL
        ,E2_SALDO AS VL_SALDO
        ,RTRIM(LTRIM(E2_HIST)) AS E2_HIST

        FROM SE2010 SE2 WITH (NOLOCK)

        INNER JOIN SA2010 SA2 WITH (NOLOCK) ON SA2.D_E_L_E_T_='' AND A2_COD=E2_FORNECE AND A2_LOJA=E2_LOJA 
        LEFT JOIN SED010 SED WITH (NOLOCK) ON SED.D_E_L_E_T_='' AND ED_CODIGO=E2_NATUREZ
        LEFT JOIN SY1000 SY1 WITH (NOLOCK) ON SY1.D_E_L_E_T_='' AND Y1_USER= REPLACE((SUBSTRING(E2_USERLGI, 3, 1)+SUBSTRING(E2_USERLGI, 7, 1)+
        SUBSTRING(E2_USERLGI, 11,1)+SUBSTRING(E2_USERLGI, 15,1)+
        SUBSTRING(E2_USERLGI, 2, 1)+SUBSTRING(E2_USERLGI, 6, 1)+
        SUBSTRING(E2_USERLGI, 10,1)+SUBSTRING(E2_USERLGI, 14,1)+
        SUBSTRING(E2_USERLGI, 1, 1)+SUBSTRING(E2_USERLGI, 5, 1)+
        SUBSTRING(E2_USERLGI, 9, 1)+SUBSTRING(E2_USERLGI, 13,1)+
        SUBSTRING(E2_USERLGI, 17,1)+SUBSTRING(E2_USERLGI, 4, 1)+
        SUBSTRING(E2_USERLGI, 8, 1)),'#@','')
        LEFT JOIN (			SELECT D2_FILIAL,D2_DOC,D2_NFORI
                            FROM SD2010 SD2
                            WHERE SD2.D_E_L_E_T_='' AND D2_NFORI<>''
                            GROUP BY D2_FILIAL,D2_DOC,D2_NFORI) COMPRA ON D2_FILIAL=E2_FILIAL AND D2_DOC=E2_NUM

        WHERE SE2.D_E_L_E_T_='' 
        --AND E2_SALDO<>'0' 
        AND E2_USUALIB NOT IN ('BLOQ.WIS','LIB.WIS')
        AND E2_TIPO = 'NDF'
        AND D2_NFORI IS NULL 
        AND A2_YPZENT <> ''
        AND E2_EMISSAO > '20250101'
        AND E2_PREFIXO <> ''

        UNION ALL

        SELECT 
        CONCAT('WCO',E2_FILIAL) AS UNIDADE
        ,E2_EMISSAO AS EMISSAO
        ,E2_NUM AS TITULO
        ,ISNULL (D2_NFORI,'')AS NF_COMPRA
        ,E2_PREFIXO AS PREFIXO
        ,E2_TIPO AS TIPO
        ,E2_NATUREZ AS NATUREZA
        ,ED_DESCRIC AS DESC_NATUREZA
        ,RTRIM(A2_NREDUZ) AS MARCA
        ,E2_VALOR AS VL_TOTAL
        ,E2_SALDO AS VL_SALDO
        ,RTRIM(LTRIM(E2_HIST)) AS E2_HIST

        FROM SE2040 SE2 WITH (NOLOCK)

        INNER JOIN SA2040 SA2 WITH (NOLOCK) ON SA2.D_E_L_E_T_='' AND A2_COD=E2_FORNECE AND A2_LOJA=E2_LOJA 
        LEFT JOIN SED040 SED WITH (NOLOCK) ON SED.D_E_L_E_T_='' AND ED_CODIGO=E2_NATUREZ
        LEFT JOIN SY1000 SY1 WITH (NOLOCK) ON SY1.D_E_L_E_T_='' AND Y1_USER= REPLACE((SUBSTRING(E2_USERLGI, 3, 1)+SUBSTRING(E2_USERLGI, 7, 1)+
        SUBSTRING(E2_USERLGI, 11,1)+SUBSTRING(E2_USERLGI, 15,1)+
        SUBSTRING(E2_USERLGI, 2, 1)+SUBSTRING(E2_USERLGI, 6, 1)+
        SUBSTRING(E2_USERLGI, 10,1)+SUBSTRING(E2_USERLGI, 14,1)+
        SUBSTRING(E2_USERLGI, 1, 1)+SUBSTRING(E2_USERLGI, 5, 1)+
        SUBSTRING(E2_USERLGI, 9, 1)+SUBSTRING(E2_USERLGI, 13,1)+
        SUBSTRING(E2_USERLGI, 17,1)+SUBSTRING(E2_USERLGI, 4, 1)+
        SUBSTRING(E2_USERLGI, 8, 1)),'#@','')
        LEFT JOIN (			SELECT D2_FILIAL,D2_DOC,D2_NFORI
                            FROM SD2040 SD2
                            WHERE SD2.D_E_L_E_T_='' AND D2_NFORI<>''
                            GROUP BY D2_FILIAL,D2_DOC,D2_NFORI) COMPRA ON D2_FILIAL=E2_FILIAL AND D2_DOC=E2_NUM

        WHERE SE2.D_E_L_E_T_='' 
        --AND E2_SALDO<>'0' 
        AND E2_USUALIB NOT IN ('BLOQ.WIS','LIB.WIS')
        AND E2_TIPO = 'NDF'
        AND D2_NFORI IS NULL 
        AND A2_YPZENT <> ''
        AND E2_EMISSAO > '20250101'
        AND E2_PREFIXO <> ''

        UNION ALL

        SELECT 
        CONCAT('WSP',E2_FILIAL) AS UNIDADE
        ,E2_EMISSAO AS EMISSAO
        ,E2_NUM AS TITULO
        ,ISNULL (D2_NFORI,'')AS NF_COMPRA
        ,E2_PREFIXO AS PREFIXO
        ,E2_TIPO AS TIPO
        ,E2_NATUREZ AS NATUREZA
        ,ED_DESCRIC AS DESC_NATUREZA
        ,RTRIM(A2_NREDUZ) AS MARCA
        ,E2_VALOR AS VL_TOTAL
        ,E2_SALDO AS VL_SALDO
        ,RTRIM(LTRIM(E2_HIST)) AS E2_HIST

        FROM SE2050 SE2 WITH (NOLOCK)

        INNER JOIN SA2050 SA2 WITH (NOLOCK) ON SA2.D_E_L_E_T_='' AND A2_COD=E2_FORNECE AND A2_LOJA=E2_LOJA 
        LEFT JOIN SED050 SED WITH (NOLOCK) ON SED.D_E_L_E_T_='' AND ED_CODIGO=E2_NATUREZ
        LEFT JOIN SY1000 SY1 WITH (NOLOCK) ON SY1.D_E_L_E_T_='' AND Y1_USER= REPLACE((SUBSTRING(E2_USERLGI, 3, 1)+SUBSTRING(E2_USERLGI, 7, 1)+
        SUBSTRING(E2_USERLGI, 11,1)+SUBSTRING(E2_USERLGI, 15,1)+
        SUBSTRING(E2_USERLGI, 2, 1)+SUBSTRING(E2_USERLGI, 6, 1)+
        SUBSTRING(E2_USERLGI, 10,1)+SUBSTRING(E2_USERLGI, 14,1)+
        SUBSTRING(E2_USERLGI, 1, 1)+SUBSTRING(E2_USERLGI, 5, 1)+
        SUBSTRING(E2_USERLGI, 9, 1)+SUBSTRING(E2_USERLGI, 13,1)+
        SUBSTRING(E2_USERLGI, 17,1)+SUBSTRING(E2_USERLGI, 4, 1)+
        SUBSTRING(E2_USERLGI, 8, 1)),'#@','')
        LEFT JOIN (			SELECT D2_FILIAL,D2_DOC,D2_NFORI
                            FROM SD2050 SD2
                            WHERE SD2.D_E_L_E_T_='' AND D2_NFORI<>''
                            GROUP BY D2_FILIAL,D2_DOC,D2_NFORI) COMPRA ON D2_FILIAL=E2_FILIAL AND D2_DOC=E2_NUM

        WHERE SE2.D_E_L_E_T_='' 
        --AND E2_SALDO<>'0' 
        AND E2_USUALIB NOT IN ('BLOQ.WIS','LIB.WIS')
        AND E2_TIPO = 'NDF'
        AND D2_NFORI IS NULL 
        AND A2_YPZENT <> ''
        AND E2_EMISSAO > '20250101'
        AND E2_PREFIXO <> ''

        UNION ALL

        SELECT 
        CONCAT('WSUL',E2_FILIAL) AS UNIDADE
        ,E2_EMISSAO AS EMISSAO
        ,E2_NUM AS TITULO
        ,ISNULL (D2_NFORI,'')AS NF_COMPRA
        ,E2_PREFIXO AS PREFIXO
        ,E2_TIPO AS TIPO
        ,E2_NATUREZ AS NATUREZA
        ,ED_DESCRIC AS DESC_NATUREZA
        ,RTRIM(A2_NREDUZ) AS MARCA
        ,E2_VALOR AS VL_TOTAL
        ,E2_SALDO AS VL_SALDO
        ,RTRIM(LTRIM(E2_HIST)) AS E2_HIST

        FROM SE2080 SE2 WITH (NOLOCK)

        INNER JOIN SA2080 SA2 WITH (NOLOCK) ON SA2.D_E_L_E_T_='' AND A2_COD=E2_FORNECE AND A2_LOJA=E2_LOJA 
        LEFT JOIN SED080 SED WITH (NOLOCK) ON SED.D_E_L_E_T_='' AND ED_CODIGO=E2_NATUREZ
        LEFT JOIN SY1000 SY1 WITH (NOLOCK) ON SY1.D_E_L_E_T_='' AND Y1_USER= REPLACE((SUBSTRING(E2_USERLGI, 3, 1)+SUBSTRING(E2_USERLGI, 7, 1)+
        SUBSTRING(E2_USERLGI, 11,1)+SUBSTRING(E2_USERLGI, 15,1)+
        SUBSTRING(E2_USERLGI, 2, 1)+SUBSTRING(E2_USERLGI, 6, 1)+
        SUBSTRING(E2_USERLGI, 10,1)+SUBSTRING(E2_USERLGI, 14,1)+
        SUBSTRING(E2_USERLGI, 1, 1)+SUBSTRING(E2_USERLGI, 5, 1)+
        SUBSTRING(E2_USERLGI, 9, 1)+SUBSTRING(E2_USERLGI, 13,1)+
        SUBSTRING(E2_USERLGI, 17,1)+SUBSTRING(E2_USERLGI, 4, 1)+
        SUBSTRING(E2_USERLGI, 8, 1)),'#@','')
        LEFT JOIN (			SELECT D2_FILIAL,D2_DOC,D2_NFORI
                            FROM SD2080 SD2
                            WHERE SD2.D_E_L_E_T_='' AND D2_NFORI<>''
                            GROUP BY D2_FILIAL,D2_DOC,D2_NFORI) COMPRA ON D2_FILIAL=E2_FILIAL AND D2_DOC=E2_NUM

        WHERE SE2.D_E_L_E_T_='' 
        --AND E2_SALDO<>'0' 
        AND E2_USUALIB NOT IN ('BLOQ.WIS','LIB.WIS')
        AND E2_TIPO = 'NDF'
        AND D2_NFORI IS NULL 
        AND A2_YPZENT <> ''
        AND E2_EMISSAO > '20250101'
        AND E2_PREFIXO <> ''

        UNION ALL

        SELECT 
        CONCAT('WNE',E2_FILIAL) AS UNIDADE
        ,E2_EMISSAO AS EMISSAO
        ,E2_NUM AS TITULO
        ,ISNULL (D2_NFORI,'')AS NF_COMPRA
        ,E2_PREFIXO AS PREFIXO
        ,E2_TIPO AS TIPO
        ,E2_NATUREZ AS NATUREZA
        ,ED_DESCRIC AS DESC_NATUREZA
        ,RTRIM(A2_NREDUZ) AS MARCA
        ,E2_VALOR AS VL_TOTAL
        ,E2_SALDO AS VL_SALDO
        ,RTRIM(LTRIM(E2_HIST)) AS E2_HIST

        FROM SE2090 SE2 WITH (NOLOCK)

        INNER JOIN SA2090 SA2 WITH (NOLOCK) ON SA2.D_E_L_E_T_='' AND A2_COD=E2_FORNECE AND A2_LOJA=E2_LOJA 
        LEFT JOIN SED090 SED WITH (NOLOCK) ON SED.D_E_L_E_T_='' AND ED_CODIGO=E2_NATUREZ
        LEFT JOIN SY1000 SY1 WITH (NOLOCK) ON SY1.D_E_L_E_T_='' AND Y1_USER= REPLACE((SUBSTRING(E2_USERLGI, 3, 1)+SUBSTRING(E2_USERLGI, 7, 1)+
        SUBSTRING(E2_USERLGI, 11,1)+SUBSTRING(E2_USERLGI, 15,1)+
        SUBSTRING(E2_USERLGI, 2, 1)+SUBSTRING(E2_USERLGI, 6, 1)+
        SUBSTRING(E2_USERLGI, 10,1)+SUBSTRING(E2_USERLGI, 14,1)+
        SUBSTRING(E2_USERLGI, 1, 1)+SUBSTRING(E2_USERLGI, 5, 1)+
        SUBSTRING(E2_USERLGI, 9, 1)+SUBSTRING(E2_USERLGI, 13,1)+
        SUBSTRING(E2_USERLGI, 17,1)+SUBSTRING(E2_USERLGI, 4, 1)+
        SUBSTRING(E2_USERLGI, 8, 1)),'#@','')
        LEFT JOIN (			SELECT D2_FILIAL,D2_DOC,D2_NFORI
                            FROM SD2090 SD2
                            WHERE SD2.D_E_L_E_T_='' AND D2_NFORI<>''
                            GROUP BY D2_FILIAL,D2_DOC,D2_NFORI) COMPRA ON D2_FILIAL=E2_FILIAL AND D2_DOC=E2_NUM

        WHERE SE2.D_E_L_E_T_='' 
        --AND E2_SALDO<>'0' 
        AND E2_USUALIB NOT IN ('BLOQ.WIS','LIB.WIS')
        AND E2_TIPO = 'NDF'
        AND D2_NFORI IS NULL 
        AND A2_YPZENT <> ''
        AND E2_EMISSAO > '20250101'
        AND E2_PREFIXO <> ''

        UNION ALL

        SELECT 
        CONCAT('WMG',E2_FILIAL) AS UNIDADE
        ,E2_EMISSAO AS EMISSAO
        ,E2_NUM AS TITULO
        ,ISNULL (D2_NFORI,'')AS NF_COMPRA
        ,E2_PREFIXO AS PREFIXO
        ,E2_TIPO AS TIPO
        ,E2_NATUREZ AS NATUREZA
        ,ED_DESCRIC AS DESC_NATUREZA
        ,RTRIM(A2_NREDUZ) AS MARCA
        ,E2_VALOR AS VL_TOTAL
        ,E2_SALDO AS VL_SALDO
        ,RTRIM(LTRIM(E2_HIST)) AS E2_HIST

        FROM SE2300 SE2 WITH (NOLOCK)

        INNER JOIN SA2300 SA2 WITH (NOLOCK) ON SA2.D_E_L_E_T_='' AND A2_COD=E2_FORNECE AND A2_LOJA=E2_LOJA 
        LEFT JOIN SED300 SED WITH (NOLOCK) ON SED.D_E_L_E_T_='' AND ED_CODIGO=E2_NATUREZ
        LEFT JOIN SY1000 SY1 WITH (NOLOCK) ON SY1.D_E_L_E_T_='' AND Y1_USER= REPLACE((SUBSTRING(E2_USERLGI, 3, 1)+SUBSTRING(E2_USERLGI, 7, 1)+
        SUBSTRING(E2_USERLGI, 11,1)+SUBSTRING(E2_USERLGI, 15,1)+
        SUBSTRING(E2_USERLGI, 2, 1)+SUBSTRING(E2_USERLGI, 6, 1)+
        SUBSTRING(E2_USERLGI, 10,1)+SUBSTRING(E2_USERLGI, 14,1)+
        SUBSTRING(E2_USERLGI, 1, 1)+SUBSTRING(E2_USERLGI, 5, 1)+
        SUBSTRING(E2_USERLGI, 9, 1)+SUBSTRING(E2_USERLGI, 13,1)+
        SUBSTRING(E2_USERLGI, 17,1)+SUBSTRING(E2_USERLGI, 4, 1)+
        SUBSTRING(E2_USERLGI, 8, 1)),'#@','')
        LEFT JOIN (			SELECT D2_FILIAL,D2_DOC,D2_NFORI
                            FROM SD2300 SD2
                            WHERE SD2.D_E_L_E_T_='' AND D2_NFORI<>''
                            GROUP BY D2_FILIAL,D2_DOC,D2_NFORI) COMPRA ON D2_FILIAL=E2_FILIAL AND D2_DOC=E2_NUM

        WHERE SE2.D_E_L_E_T_='' 
        AND E2_FILIAL = '03'
        --AND E2_SALDO<>'0' 
        AND E2_USUALIB NOT IN ('BLOQ.WIS','LIB.WIS')
        AND E2_TIPO = 'NDF'
        AND D2_NFORI IS NULL 
        AND A2_YPZENT <> ''
        AND E2_EMISSAO > '20250101'
        AND E2_PREFIXO <> ''
        """

        qvg = """
            SELECT
            'WMG_03' AS UNIDADE,
            C6_NUM,
            RTRIM(C6_DESCGRU) AS MARCA,
            C6_PRODUTO AS PRODUTO,
            C6_QTDVEN AS QUANTIDADE,
            C6_YPRTAB AS [PREÇO TABELA],
            C6_PRCVEN AS [PREÇO VENDA],
            C6_VALOR AS TOTAL,
            C5_EMISSAO AS EMISSAO,
            C5_YPOLITI AS POLITICA,
            LEFT(C5_EMISSAO,4) AS ANO,
            RIGHT(LEFT(C5_EMISSAO,6),2) AS MES,
            RIGHT(C5_EMISSAO,2) AS DIA,
            CASE 
                WHEN ISNUMERIC(REPLACE(RTRIM(C5_YVALCUP), '%', '')) = 1 
                THEN CAST(REPLACE(RTRIM(C5_YVALCUP), '%', '') AS DECIMAL(10,4)) / 100
                ELSE 0 
            END AS CUPOM,
            CASE WHEN C5_CONDPAG IN ('B01',
        'F38',
        'V38',
        'V60',
        'V62',
        'V63',
        'V77') THEN 0.03
        ELSE 0
        END
            AS [DESCONTO A VISTA],
        
            CASE 
                WHEN RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') THEN 'PNM'
                WHEN RTRIM(C6_DESCGRU) = 'PANTHER' THEN 'PNM IMP'
                WHEN RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') THEN 'NAC PREMIUM'
                ELSE 'NACIONAL'
            END AS CLASSIFICACAO,
            CASE 
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0001') THEN 0.03
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0002') THEN 0.05
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0001') THEN 0
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0002') THEN 0.04
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (C5_YPOLITI = '0001') THEN 0
                WHEN (C5_YPOLITI = '0002') THEN 0
                WHEN (C5_YPOLITI = '0003') THEN 0.02
                WHEN (C5_YPOLITI = '0004') THEN 0.03
                WHEN (C5_YPOLITI = '0005') THEN 0.03
        
                ELSE NULL
            END AS [DESCONTO POLITICA],
        
        
        C6_YPRTAB * (COALESCE(
            CASE 
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0001') THEN 0.03
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0002') THEN 0.05
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0001') THEN 0
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0002') THEN 0.04
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (C5_YPOLITI = '0001') THEN 0
                WHEN (C5_YPOLITI = '0002') THEN 0
                WHEN (C5_YPOLITI = '0003') THEN 0.02
                WHEN (C5_YPOLITI = '0004') THEN 0.03
                WHEN (C5_YPOLITI = '0005') THEN 0.03
        
                ELSE NULL
            END, 0)
        ) AS [VALOR DESCONTO POLÍTICA],
        
        C6_YPRTAB * (COALESCE(
        CASE WHEN C5_CONDPAG IN ('B01',
        'F38',
        'V38',
        'V60',
        'V62',
        'V63',
        'V77') THEN 0.03
        ELSE 0
        END, 0)
        ) AS [VALOR DESCONTO CONDIÇÃO],
        
        
        C6_YPRTAB * (COALESCE(
        CASE 
                WHEN ISNUMERIC(REPLACE(RTRIM(C5_YVALCUP), '%', '')) = 1 
                THEN CAST(REPLACE(RTRIM(C5_YVALCUP), '%', '') AS DECIMAL(10,4)) / 100
                ELSE 0 
            END, 0)
        ) AS [VALOR DESCONTO CUPOM],
        
        C6_YPRTAB - C6_PRCVEN AS [DESCONTO TOTAL]
        
        FROM SC6300
        
        LEFT JOIN SC5300 ON C5_FILIAL = C6_FILIAL AND C5_NUM = C6_NUM
        JOIN SE4300 E4 ON C5_CONDPAG = E4_CODIGO AND C6_FILIAL = E4_FILIAL
        JOIN SB1000 ON B1_COD = C6_PRODUTO 
        
        WHERE 
        C5_EMISSAO > '20250101'
        AND C6_FILIAL = '03'
        AND E4.D_E_L_E_T_ = ''
        AND B1_YFINALI = '1'
        AND B1_IMPORT = 'N'

        UNION ALL 

        SELECT
            'MB_FILIAL' AS UNIDADE,
            C6_NUM,
            RTRIM(C6_DESCGRU) AS MARCA,
            C6_PRODUTO AS PRODUTO,
            C6_QTDVEN AS QUANTIDADE,
            C6_YPRTAB AS [PREÇO TABELA],
            C6_PRCVEN AS [PREÇO VENDA],
            C6_VALOR AS TOTAL,
            C5_EMISSAO AS EMISSAO,
            C5_YPOLITI AS POLITICA,
            LEFT(C5_EMISSAO,4) AS ANO,
            RIGHT(LEFT(C5_EMISSAO,6),2) AS MES,
            RIGHT(C5_EMISSAO,2) AS DIA,
            CASE 
                WHEN ISNUMERIC(REPLACE(RTRIM(C5_YVALCUP), '%', '')) = 1 
                THEN CAST(REPLACE(RTRIM(C5_YVALCUP), '%', '') AS DECIMAL(10,4)) / 100
                ELSE 0 
            END AS CUPOM,
            CASE WHEN C5_CONDPAG IN ('B01',
        'F38',
        'V38',
        'V60',
        'V62',
        'V63',
        'V77') THEN 0.03
        ELSE 0
        END
            AS [DESCONTO A VISTA],
        
            CASE 
                WHEN RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') THEN 'PNM'
                WHEN RTRIM(C6_DESCGRU) = 'PANTHER' THEN 'PNM IMP'
                WHEN RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') THEN 'NAC PREMIUM'
                ELSE 'NACIONAL'
            END AS CLASSIFICACAO,
            CASE 
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0001') THEN 0.03
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0002') THEN 0.05
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0001') THEN 0
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0002') THEN 0.04
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (C5_YPOLITI = '0001') THEN 0
                WHEN (C5_YPOLITI = '0002') THEN 0
                WHEN (C5_YPOLITI = '0003') THEN 0.02
                WHEN (C5_YPOLITI = '0004') THEN 0.03
                WHEN (C5_YPOLITI = '0005') THEN 0.03
        
                ELSE NULL
            END AS [DESCONTO POLITICA],
        
        
        C6_YPRTAB * (COALESCE(
            CASE 
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0001') THEN 0.03
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0002') THEN 0.05
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0001') THEN 0
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0002') THEN 0.04
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (C5_YPOLITI = '0001') THEN 0
                WHEN (C5_YPOLITI = '0002') THEN 0
                WHEN (C5_YPOLITI = '0003') THEN 0.02
                WHEN (C5_YPOLITI = '0004') THEN 0.03
                WHEN (C5_YPOLITI = '0005') THEN 0.03
        
                ELSE NULL
            END, 0)
        ) AS [VALOR DESCONTO POLÍTICA],
        
        C6_YPRTAB * (COALESCE(
        CASE WHEN C5_CONDPAG IN ('B01',
        'F38',
        'V38',
        'V60',
        'V62',
        'V63',
        'V77') THEN 0.03
        ELSE 0
        END, 0)
        ) AS [VALOR DESCONTO CONDIÇÃO],
        
        
        C6_YPRTAB * (COALESCE(
        CASE 
                WHEN ISNUMERIC(REPLACE(RTRIM(C5_YVALCUP), '%', '')) = 1 
                THEN CAST(REPLACE(RTRIM(C5_YVALCUP), '%', '') AS DECIMAL(10,4)) / 100
                ELSE 0 
            END, 0)
        ) AS [VALOR DESCONTO CUPOM],
        
        C6_YPRTAB - C6_PRCVEN AS [DESCONTO TOTAL]
        
        FROM SC6010
        
        LEFT JOIN SC5010 ON C5_FILIAL = C6_FILIAL AND C5_NUM = C6_NUM
        JOIN SE4010 E4 ON C5_CONDPAG = E4_CODIGO AND C6_FILIAL = E4_FILIAL
        JOIN SB1000 ON B1_COD = C6_PRODUTO 
        
        WHERE 
        C5_EMISSAO > '20250101'
        AND C6_FILIAL = '02'
        AND E4.D_E_L_E_T_ = ''
        AND B1_YFINALI = '1'
        AND B1_IMPORT = 'N'

        UNION ALL 

        SELECT
            'LM' AS UNIDADE,
            C6_NUM,
            RTRIM(C6_DESCGRU) AS MARCA,
            C6_PRODUTO AS PRODUTO,
            C6_QTDVEN AS QUANTIDADE,
            C6_YPRTAB AS [PREÇO TABELA],
            C6_PRCVEN AS [PREÇO VENDA],
            C6_VALOR AS TOTAL,
            C5_EMISSAO AS EMISSAO,
            C5_YPOLITI AS POLITICA,
            LEFT(C5_EMISSAO,4) AS ANO,
            RIGHT(LEFT(C5_EMISSAO,6),2) AS MES,
            RIGHT(C5_EMISSAO,2) AS DIA,
            CASE 
                WHEN ISNUMERIC(REPLACE(RTRIM(C5_YVALCUP), '%', '')) = 1 
                THEN CAST(REPLACE(RTRIM(C5_YVALCUP), '%', '') AS DECIMAL(10,4)) / 100
                ELSE 0 
            END AS CUPOM,
            CASE WHEN C5_CONDPAG IN ('B01',
        'F38',
        'V38',
        'V60',
        'V62',
        'V63',
        'V77') THEN 0.03
        ELSE 0
        END
            AS [DESCONTO A VISTA],
        
            CASE 
                WHEN RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') THEN 'PNM'
                WHEN RTRIM(C6_DESCGRU) = 'PANTHER' THEN 'PNM IMP'
                WHEN RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') THEN 'NAC PREMIUM'
                ELSE 'NACIONAL'
            END AS CLASSIFICACAO,
            CASE 
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0001') THEN 0.03
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0002') THEN 0.05
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0001') THEN 0
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0002') THEN 0.04
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (C5_YPOLITI = '0001') THEN 0
                WHEN (C5_YPOLITI = '0002') THEN 0
                WHEN (C5_YPOLITI = '0003') THEN 0.02
                WHEN (C5_YPOLITI = '0004') THEN 0.03
                WHEN (C5_YPOLITI = '0005') THEN 0.03
        
                ELSE NULL
            END AS [DESCONTO POLITICA],
        
        
        C6_YPRTAB * (COALESCE(
            CASE 
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0001') THEN 0.03
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0002') THEN 0.05
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0001') THEN 0
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0002') THEN 0.04
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (C5_YPOLITI = '0001') THEN 0
                WHEN (C5_YPOLITI = '0002') THEN 0
                WHEN (C5_YPOLITI = '0003') THEN 0.02
                WHEN (C5_YPOLITI = '0004') THEN 0.03
                WHEN (C5_YPOLITI = '0005') THEN 0.03
        
                ELSE NULL
            END, 0)
        ) AS [VALOR DESCONTO POLÍTICA],
        
        C6_YPRTAB * (COALESCE(
        CASE WHEN C5_CONDPAG IN ('B01',
        'F38',
        'V38',
        'V60',
        'V62',
        'V63',
        'V77') THEN 0.03
        ELSE 0
        END, 0)
        ) AS [VALOR DESCONTO CONDIÇÃO],
        
        
        C6_YPRTAB * (COALESCE(
        CASE 
                WHEN ISNUMERIC(REPLACE(RTRIM(C5_YVALCUP), '%', '')) = 1 
                THEN CAST(REPLACE(RTRIM(C5_YVALCUP), '%', '') AS DECIMAL(10,4)) / 100
                ELSE 0 
            END, 0)
        ) AS [VALOR DESCONTO CUPOM],
        
        C6_YPRTAB - C6_PRCVEN AS [DESCONTO TOTAL]
        
        FROM SC6020
        
        LEFT JOIN SC5020 ON C5_FILIAL = C6_FILIAL AND C5_NUM = C6_NUM
        JOIN SE4020 E4 ON C5_CONDPAG = E4_CODIGO 
        JOIN SB1000 ON B1_COD = C6_PRODUTO 
        
        WHERE 
        C5_EMISSAO > '20250101'
        AND C6_FILIAL = '02'
        AND E4.D_E_L_E_T_ = ''
        AND B1_YFINALI = '1'
        AND B1_IMPORT = 'N'

        UNION ALL 

        SELECT
            'WCO' AS UNIDADE,
            C6_NUM,
            RTRIM(C6_DESCGRU) AS MARCA,
            C6_PRODUTO AS PRODUTO,
            C6_QTDVEN AS QUANTIDADE,
            C6_YPRTAB AS [PREÇO TABELA],
            C6_PRCVEN AS [PREÇO VENDA],
            C6_VALOR AS TOTAL,
            C5_EMISSAO AS EMISSAO,
            C5_YPOLITI AS POLITICA,
            LEFT(C5_EMISSAO,4) AS ANO,
            RIGHT(LEFT(C5_EMISSAO,6),2) AS MES,
            RIGHT(C5_EMISSAO,2) AS DIA,
            CASE 
                WHEN ISNUMERIC(REPLACE(RTRIM(C5_YVALCUP), '%', '')) = 1 
                THEN CAST(REPLACE(RTRIM(C5_YVALCUP), '%', '') AS DECIMAL(10,4)) / 100
                ELSE 0 
            END AS CUPOM,
            CASE WHEN C5_CONDPAG IN ('B01',
        'F38',
        'V38',
        'V60',
        'V62',
        'V63',
        'V77') THEN 0.03
        ELSE 0
        END
            AS [DESCONTO A VISTA],
        
            CASE 
                WHEN RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') THEN 'PNM'
                WHEN RTRIM(C6_DESCGRU) = 'PANTHER' THEN 'PNM IMP'
                WHEN RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') THEN 'NAC PREMIUM'
                ELSE 'NACIONAL'
            END AS CLASSIFICACAO,
            CASE 
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0001') THEN 0.03
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0002') THEN 0.05
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0001') THEN 0
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0002') THEN 0.04
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (C5_YPOLITI = '0001') THEN 0
                WHEN (C5_YPOLITI = '0002') THEN 0
                WHEN (C5_YPOLITI = '0003') THEN 0.02
                WHEN (C5_YPOLITI = '0004') THEN 0.03
                WHEN (C5_YPOLITI = '0005') THEN 0.03
        
                ELSE NULL
            END AS [DESCONTO POLITICA],
        
        
        C6_YPRTAB * (COALESCE(
            CASE 
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0001') THEN 0.03
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0002') THEN 0.05
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0001') THEN 0
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0002') THEN 0.04
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (C5_YPOLITI = '0001') THEN 0
                WHEN (C5_YPOLITI = '0002') THEN 0
                WHEN (C5_YPOLITI = '0003') THEN 0.02
                WHEN (C5_YPOLITI = '0004') THEN 0.03
                WHEN (C5_YPOLITI = '0005') THEN 0.03
        
                ELSE NULL
            END, 0)
        ) AS [VALOR DESCONTO POLÍTICA],
        
        C6_YPRTAB * (COALESCE(
        CASE WHEN C5_CONDPAG IN ('B01',
        'F38',
        'V38',
        'V60',
        'V62',
        'V63',
        'V77') THEN 0.03
        ELSE 0
        END, 0)
        ) AS [VALOR DESCONTO CONDIÇÃO],
        
        
        C6_YPRTAB * (COALESCE(
        CASE 
                WHEN ISNUMERIC(REPLACE(RTRIM(C5_YVALCUP), '%', '')) = 1 
                THEN CAST(REPLACE(RTRIM(C5_YVALCUP), '%', '') AS DECIMAL(10,4)) / 100
                ELSE 0 
            END, 0)
        ) AS [VALOR DESCONTO CUPOM],
        
        C6_YPRTAB - C6_PRCVEN AS [DESCONTO TOTAL]
        
        FROM SC6040
        
        LEFT JOIN SC5040 ON C5_FILIAL = C6_FILIAL AND C5_NUM = C6_NUM
        JOIN SE4040 E4 ON C5_CONDPAG = E4_CODIGO AND C6_FILIAL = E4_FILIAL
        JOIN SB1000 ON B1_COD = C6_PRODUTO 
        
        WHERE 
        C5_EMISSAO > '20250101'
        AND C6_FILIAL = '01'
        AND E4.D_E_L_E_T_ = ''
        AND B1_YFINALI = '1'
        AND B1_IMPORT = 'N'

        UNION ALL 

        SELECT
            'WSP' AS UNIDADE,
            C6_NUM,
            RTRIM(C6_DESCGRU) AS MARCA,
            C6_PRODUTO AS PRODUTO,
            C6_QTDVEN AS QUANTIDADE,
            C6_YPRTAB AS [PREÇO TABELA],
            C6_PRCVEN AS [PREÇO VENDA],
            C6_VALOR AS TOTAL,
            C5_EMISSAO AS EMISSAO,
            C5_YPOLITI AS POLITICA,
            LEFT(C5_EMISSAO,4) AS ANO,
            RIGHT(LEFT(C5_EMISSAO,6),2) AS MES,
            RIGHT(C5_EMISSAO,2) AS DIA,
            CASE 
                WHEN ISNUMERIC(REPLACE(RTRIM(C5_YVALCUP), '%', '')) = 1 
                THEN CAST(REPLACE(RTRIM(C5_YVALCUP), '%', '') AS DECIMAL(10,4)) / 100
                ELSE 0 
            END AS CUPOM,
            CASE WHEN C5_CONDPAG IN ('B01',
        'F38',
        'V38',
        'V60',
        'V62',
        'V63',
        'V77') THEN 0.03
        ELSE 0
        END
            AS [DESCONTO A VISTA],
        
            CASE 
                WHEN RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') THEN 'PNM'
                WHEN RTRIM(C6_DESCGRU) = 'PANTHER' THEN 'PNM IMP'
                WHEN RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') THEN 'NAC PREMIUM'
                ELSE 'NACIONAL'
            END AS CLASSIFICACAO,
            CASE 
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0001') THEN 0.03
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0002') THEN 0.05
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0001') THEN 0
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0002') THEN 0.04
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (C5_YPOLITI = '0001') THEN 0
                WHEN (C5_YPOLITI = '0002') THEN 0
                WHEN (C5_YPOLITI = '0003') THEN 0.02
                WHEN (C5_YPOLITI = '0004') THEN 0.03
                WHEN (C5_YPOLITI = '0005') THEN 0.03
        
                ELSE NULL
            END AS [DESCONTO POLITICA],
        
        
        C6_YPRTAB * (COALESCE(
            CASE 
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0001') THEN 0.03
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0002') THEN 0.05
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0001') THEN 0
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0002') THEN 0.04
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (C5_YPOLITI = '0001') THEN 0
                WHEN (C5_YPOLITI = '0002') THEN 0
                WHEN (C5_YPOLITI = '0003') THEN 0.02
                WHEN (C5_YPOLITI = '0004') THEN 0.03
                WHEN (C5_YPOLITI = '0005') THEN 0.03
        
                ELSE NULL
            END, 0)
        ) AS [VALOR DESCONTO POLÍTICA],
        
        C6_YPRTAB * (COALESCE(
        CASE WHEN C5_CONDPAG IN ('B01',
        'F38',
        'V38',
        'V60',
        'V62',
        'V63',
        'V77') THEN 0.03
        ELSE 0
        END, 0)
        ) AS [VALOR DESCONTO CONDIÇÃO],
        
        
        C6_YPRTAB * (COALESCE(
        CASE 
                WHEN ISNUMERIC(REPLACE(RTRIM(C5_YVALCUP), '%', '')) = 1 
                THEN CAST(REPLACE(RTRIM(C5_YVALCUP), '%', '') AS DECIMAL(10,4)) / 100
                ELSE 0 
            END, 0)
        ) AS [VALOR DESCONTO CUPOM],
        
        C6_YPRTAB - C6_PRCVEN AS [DESCONTO TOTAL]
        
        FROM SC6050
        
        LEFT JOIN SC5050 ON C5_FILIAL = C6_FILIAL AND C5_NUM = C6_NUM
        JOIN SE4050 E4 ON C5_CONDPAG = E4_CODIGO AND C6_FILIAL = E4_FILIAL
        JOIN SB1000 ON B1_COD = C6_PRODUTO 
        
        WHERE 
        C5_EMISSAO > '20250101'
        AND C6_FILIAL = '01'
        AND E4.D_E_L_E_T_ = ''
        AND B1_YFINALI = '1'
        AND B1_IMPORT = 'N'

        UNION ALL 

        SELECT
            'WSUL' AS UNIDADE,
            C6_NUM,
            RTRIM(C6_DESCGRU) AS MARCA,
            C6_PRODUTO AS PRODUTO,
            C6_QTDVEN AS QUANTIDADE,
            C6_YPRTAB AS [PREÇO TABELA],
            C6_PRCVEN AS [PREÇO VENDA],
            C6_VALOR AS TOTAL,
            C5_EMISSAO AS EMISSAO,
            C5_YPOLITI AS POLITICA,
            LEFT(C5_EMISSAO,4) AS ANO,
            RIGHT(LEFT(C5_EMISSAO,6),2) AS MES,
            RIGHT(C5_EMISSAO,2) AS DIA,
            CASE 
                WHEN ISNUMERIC(REPLACE(RTRIM(C5_YVALCUP), '%', '')) = 1 
                THEN CAST(REPLACE(RTRIM(C5_YVALCUP), '%', '') AS DECIMAL(10,4)) / 100
                ELSE 0 
            END AS CUPOM,
            CASE WHEN C5_CONDPAG IN ('B01',
        'F38',
        'V38',
        'V60',
        'V62',
        'V63',
        'V77') THEN 0.03
        ELSE 0
        END
            AS [DESCONTO A VISTA],
        
            CASE 
                WHEN RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') THEN 'PNM'
                WHEN RTRIM(C6_DESCGRU) = 'PANTHER' THEN 'PNM IMP'
                WHEN RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') THEN 'NAC PREMIUM'
                ELSE 'NACIONAL'
            END AS CLASSIFICACAO,
            CASE 
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0001') THEN 0.03
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0002') THEN 0.05
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0001') THEN 0
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0002') THEN 0.04
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (C5_YPOLITI = '0001') THEN 0
                WHEN (C5_YPOLITI = '0002') THEN 0
                WHEN (C5_YPOLITI = '0003') THEN 0.02
                WHEN (C5_YPOLITI = '0004') THEN 0.03
                WHEN (C5_YPOLITI = '0005') THEN 0.03
        
                ELSE NULL
            END AS [DESCONTO POLITICA],
        
        
        C6_YPRTAB * (COALESCE(
            CASE 
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0001') THEN 0.03
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0002') THEN 0.05
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0001') THEN 0
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0002') THEN 0.04
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (C5_YPOLITI = '0001') THEN 0
                WHEN (C5_YPOLITI = '0002') THEN 0
                WHEN (C5_YPOLITI = '0003') THEN 0.02
                WHEN (C5_YPOLITI = '0004') THEN 0.03
                WHEN (C5_YPOLITI = '0005') THEN 0.03
        
                ELSE NULL
            END, 0)
        ) AS [VALOR DESCONTO POLÍTICA],
        
        C6_YPRTAB * (COALESCE(
        CASE WHEN C5_CONDPAG IN ('B01',
        'F38',
        'V38',
        'V60',
        'V62',
        'V63',
        'V77') THEN 0.03
        ELSE 0
        END, 0)
        ) AS [VALOR DESCONTO CONDIÇÃO],
        
        
        C6_YPRTAB * (COALESCE(
        CASE 
                WHEN ISNUMERIC(REPLACE(RTRIM(C5_YVALCUP), '%', '')) = 1 
                THEN CAST(REPLACE(RTRIM(C5_YVALCUP), '%', '') AS DECIMAL(10,4)) / 100
                ELSE 0 
            END, 0)
        ) AS [VALOR DESCONTO CUPOM],
        
        C6_YPRTAB - C6_PRCVEN AS [DESCONTO TOTAL]
        
        FROM SC6080
        
        LEFT JOIN SC5080 ON C5_FILIAL = C6_FILIAL AND C5_NUM = C6_NUM
        JOIN SE4080 E4 ON C5_CONDPAG = E4_CODIGO AND C6_FILIAL = E4_FILIAL
        JOIN SB1000 ON B1_COD = C6_PRODUTO 
        
        WHERE 
        C5_EMISSAO > '20250101'
        AND C6_FILIAL = '01'
        AND E4.D_E_L_E_T_ = ''
        AND B1_YFINALI = '1'
        AND B1_IMPORT = 'N'

        UNION ALL 

        SELECT
            'WNE_01' AS UNIDADE,
            C6_NUM,
            RTRIM(C6_DESCGRU) AS MARCA,
            C6_PRODUTO AS PRODUTO,
            C6_QTDVEN AS QUANTIDADE,
            C6_YPRTAB AS [PREÇO TABELA],
            C6_PRCVEN AS [PREÇO VENDA],
            C6_VALOR AS TOTAL,
            C5_EMISSAO AS EMISSAO,
            C5_YPOLITI AS POLITICA,
            LEFT(C5_EMISSAO,4) AS ANO,
            RIGHT(LEFT(C5_EMISSAO,6),2) AS MES,
            RIGHT(C5_EMISSAO,2) AS DIA,
            CASE 
                WHEN ISNUMERIC(REPLACE(RTRIM(C5_YVALCUP), '%', '')) = 1 
                THEN CAST(REPLACE(RTRIM(C5_YVALCUP), '%', '') AS DECIMAL(10,4)) / 100
                ELSE 0 
            END AS CUPOM,
            CASE WHEN C5_CONDPAG IN ('B01',
        'F38',
        'V38',
        'V60',
        'V62',
        'V63',
        'V77') THEN 0.03
        ELSE 0
        END
            AS [DESCONTO A VISTA],
        
            CASE 
                WHEN RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') THEN 'PNM'
                WHEN RTRIM(C6_DESCGRU) = 'PANTHER' THEN 'PNM IMP'
                WHEN RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') THEN 'NAC PREMIUM'
                ELSE 'NACIONAL'
            END AS CLASSIFICACAO,
            CASE 
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0001') THEN 0.03
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0002') THEN 0.05
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0001') THEN 0
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0002') THEN 0.04
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (C5_YPOLITI = '0001') THEN 0
                WHEN (C5_YPOLITI = '0002') THEN 0
                WHEN (C5_YPOLITI = '0003') THEN 0.02
                WHEN (C5_YPOLITI = '0004') THEN 0.03
                WHEN (C5_YPOLITI = '0005') THEN 0.03
        
                ELSE NULL
            END AS [DESCONTO POLITICA],
        
        
        C6_YPRTAB * (COALESCE(
            CASE 
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0001') THEN 0.03
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0002') THEN 0.05
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0001') THEN 0
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0002') THEN 0.04
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (C5_YPOLITI = '0001') THEN 0
                WHEN (C5_YPOLITI = '0002') THEN 0
                WHEN (C5_YPOLITI = '0003') THEN 0.02
                WHEN (C5_YPOLITI = '0004') THEN 0.03
                WHEN (C5_YPOLITI = '0005') THEN 0.03
        
                ELSE NULL
            END, 0)
        ) AS [VALOR DESCONTO POLÍTICA],
        
        C6_YPRTAB * (COALESCE(
        CASE WHEN C5_CONDPAG IN ('B01',
        'F38',
        'V38',
        'V60',
        'V62',
        'V63',
        'V77') THEN 0.03
        ELSE 0
        END, 0)
        ) AS [VALOR DESCONTO CONDIÇÃO],
        
        
        C6_YPRTAB * (COALESCE(
        CASE 
                WHEN ISNUMERIC(REPLACE(RTRIM(C5_YVALCUP), '%', '')) = 1 
                THEN CAST(REPLACE(RTRIM(C5_YVALCUP), '%', '') AS DECIMAL(10,4)) / 100
                ELSE 0 
            END, 0)
        ) AS [VALOR DESCONTO CUPOM],
        
        C6_YPRTAB - C6_PRCVEN AS [DESCONTO TOTAL]
        
        FROM SC6090
        
        LEFT JOIN SC5090 ON C5_FILIAL = C6_FILIAL AND C5_NUM = C6_NUM
        JOIN SE4090 E4 ON C5_CONDPAG = E4_CODIGO --AND C6_FILIAL = E4_FILIAL
        JOIN SB1000 ON B1_COD = C6_PRODUTO 
        
        WHERE 
        C5_EMISSAO > '20250101'
        AND C6_FILIAL = '01'
        AND E4.D_E_L_E_T_ = ''
        AND B1_YFINALI = '1'
        AND B1_IMPORT = 'N'

        UNION ALL 

        SELECT
            'WNE_02' AS UNIDADE,
            C6_NUM,
            RTRIM(C6_DESCGRU) AS MARCA,
            C6_PRODUTO AS PRODUTO,
            C6_QTDVEN AS QUANTIDADE,
            C6_YPRTAB AS [PREÇO TABELA],
            C6_PRCVEN AS [PREÇO VENDA],
            C6_VALOR AS TOTAL,
            C5_EMISSAO AS EMISSAO,
            C5_YPOLITI AS POLITICA,
            LEFT(C5_EMISSAO,4) AS ANO,
            RIGHT(LEFT(C5_EMISSAO,6),2) AS MES,
            RIGHT(C5_EMISSAO,2) AS DIA,
            CASE 
                WHEN ISNUMERIC(REPLACE(RTRIM(C5_YVALCUP), '%', '')) = 1 
                THEN CAST(REPLACE(RTRIM(C5_YVALCUP), '%', '') AS DECIMAL(10,4)) / 100
                ELSE 0 
            END AS CUPOM,
            CASE WHEN C5_CONDPAG IN ('B01',
        'F38',
        'V38',
        'V60',
        'V62',
        'V63',
        'V77') THEN 0.03
        ELSE 0
        END
            AS [DESCONTO A VISTA],
        
            CASE 
                WHEN RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') THEN 'PNM'
                WHEN RTRIM(C6_DESCGRU) = 'PANTHER' THEN 'PNM IMP'
                WHEN RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') THEN 'NAC PREMIUM'
                ELSE 'NACIONAL'
            END AS CLASSIFICACAO,
            CASE 
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0001') THEN 0.03
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0002') THEN 0.05
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0001') THEN 0
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0002') THEN 0.04
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (C5_YPOLITI = '0001') THEN 0
                WHEN (C5_YPOLITI = '0002') THEN 0
                WHEN (C5_YPOLITI = '0003') THEN 0.02
                WHEN (C5_YPOLITI = '0004') THEN 0.03
                WHEN (C5_YPOLITI = '0005') THEN 0.03
        
                ELSE NULL
            END AS [DESCONTO POLITICA],
        
        
        C6_YPRTAB * (COALESCE(
            CASE 
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0001') THEN 0.03
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0002') THEN 0.05
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('LEVORIN', 'MICHELIN BR') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0001') THEN 0
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0002') THEN 0.04
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0003') THEN 0.06
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0004') THEN 0.07
                WHEN (RTRIM(C6_DESCGRU) IN ('ERBS','HELIAR','SERVITEC','SCUD','ALBA','COFAP','SORETTO','SORETTO MAXI', 'YUASA', 'VEDAMOTORS', 'VAZ', 'TAURUS', 'PHILIPS', 'ORSAM', 'NGK', 'NACHI', 'METAL LEVE', 'MELC', 'MAGNETRON', 'GVS','DID','DIAFRAG','DELTACAPAS','CORTECO','COBREQ') AND C5_YPOLITI = '0005') THEN 0.08
                WHEN (C5_YPOLITI = '0001') THEN 0
                WHEN (C5_YPOLITI = '0002') THEN 0
                WHEN (C5_YPOLITI = '0003') THEN 0.02
                WHEN (C5_YPOLITI = '0004') THEN 0.03
                WHEN (C5_YPOLITI = '0005') THEN 0.03
        
                ELSE NULL
            END, 0)
        ) AS [VALOR DESCONTO POLÍTICA],
        
        C6_YPRTAB * (COALESCE(
        CASE WHEN C5_CONDPAG IN ('B01',
        'F38',
        'V38',
        'V60',
        'V62',
        'V63',
        'V77') THEN 0.03
        ELSE 0
        END, 0)
        ) AS [VALOR DESCONTO CONDIÇÃO],
        
        
        C6_YPRTAB * (COALESCE(
        CASE 
                WHEN ISNUMERIC(REPLACE(RTRIM(C5_YVALCUP), '%', '')) = 1 
                THEN CAST(REPLACE(RTRIM(C5_YVALCUP), '%', '') AS DECIMAL(10,4)) / 100
                ELSE 0 
            END, 0)
        ) AS [VALOR DESCONTO CUPOM],
        
        C6_YPRTAB - C6_PRCVEN AS [DESCONTO TOTAL]
        
        FROM SC6090
        
        LEFT JOIN SC5090 ON C5_FILIAL = C6_FILIAL AND C5_NUM = C6_NUM
        JOIN SE4090 E4 ON C5_CONDPAG = E4_CODIGO --AND C6_FILIAL = E4_FILIAL
        JOIN SB1000 ON B1_COD = C6_PRODUTO 
        
        WHERE 
        C5_EMISSAO > '20250101'
        AND C6_FILIAL = '02'
        AND E4.D_E_L_E_T_ = ''
        AND B1_YFINALI = '1'
        AND B1_IMPORT = 'N'

        """

        dbon = pd.read_sql(qbon, conn)
        dvg = pd.read_sql(qvg, conn)
        ddep = pd.read_sql(qdep, conn)
        cmv = pd.read_sql(qcmv, conn)
        obj = DataBase(dbon, dvg, ddep, cmv)
        save_to_cache(obj)
    return obj

        


dbon = DataBase.dbon
dvg = DataBase.dvg
ddep = DataBase.ddep
cmv = DataBase.cmv


dvg['CUPOM'] = dvg['CUPOM'].fillna(0)

dvg['DESCONTO_PROMOÇÃO'] = 1 - (dvg['PREÇO VENDA'] / (dvg['PREÇO TABELA'] * (1 - dvg['DESCONTO A VISTA']) * (1 - dvg['DESCONTO POLITICA']) * (1 - dvg['CUPOM'])))
dvg.loc[dvg['DESCONTO_PROMOÇÃO'] < 0, 'DESCONTO_PROMOÇÃO'] = 0

dvg['VALOR_GASTO'] = dvg['PREÇO TABELA'] * dvg['DESCONTO_PROMOÇÃO'] * dvg['QUANTIDADE']

dbon['F1_VALBRUT'] = pd.to_numeric(dbon['F1_VALBRUT'], errors='coerce')
dbon['VALOR_BONIFICADO'] = dbon['F1_VALBRUT']

ddep['VALOR_DEPOSITADO'] = ddep['VL_TOTAL']

dbon['EMISSAO'] = pd.to_datetime(dbon['EMISSAO'], format='%Y%m%d')
ddep['EMISSAO'] = pd.to_datetime(ddep['EMISSAO'], format='%Y%m%d')

dbon['MES_ANO'] = dbon['EMISSAO'].dt.strftime('%b/%Y')
ddep['MES_ANO'] = ddep['EMISSAO'].dt.strftime('%b/%Y')

mes_ano_disponiveis_bon = sorted(dbon['MES_ANO'].unique())

st.sidebar.header("Filtros")

st.sidebar.subheader("Filtro de Bonificação (dbon)")
mes_ano_selecionados_bon = st.sidebar.multiselect("Selecione os Meses/Ano de Bonificação:", mes_ano_disponiveis_bon, default=mes_ano_disponiveis_bon)

st.sidebar.subheader("Filtro de Gasto de Verba (dvg)")
anos_selecionados_gasto = st.sidebar.multiselect("Selecione os Anos de Gasto de Verba:", sorted(dvg['ANO'].unique()), default=sorted(dvg['ANO'].unique()))
meses_selecionados_gasto = st.sidebar.multiselect("Selecione os Meses de Gasto de Verba:", sorted(dvg['MES'].unique()), default=sorted(dvg['MES'].unique()))

marcas_disponiveis = sorted(dvg['MARCA'].unique())
selecionar_todas_marcas = st.sidebar.button("Selecionar Todas as Marcas")
desmarcar_todas_marcas = st.sidebar.button("Desmarcar Todas as Marcas")

# Lógica para controle dos botões
if 'marcas_selecionadas' not in st.session_state:
    st.session_state.marcas_selecionadas = marcas_disponiveis  # Estado inicial com todas as marcas selecionadas

# Atualiza o estado conforme o botão clicado
if selecionar_todas_marcas:
    st.session_state.marcas_selecionadas = marcas_disponiveis  # Seleciona todas as marcas
elif desmarcar_todas_marcas:
    st.session_state.marcas_selecionadas = []  # Desmarcar todas as marcas

# Exibe a caixa de seleção com as marcas filtradas
marcas_selecionadas = st.sidebar.multiselect("Selecione as Marcas:", marcas_disponiveis, default=st.session_state.marcas_selecionadas)

# Filtra os dados com base nas marcas selecionadas
df_filtrado_gasto = dvg[(dvg['ANO'].isin(anos_selecionados_gasto)) & (dvg['MES'].isin(meses_selecionados_gasto)) & (dvg['MARCA'].isin(marcas_selecionadas))]
df_filtrado_bon = dbon[dbon['MES_ANO'].isin(mes_ano_selecionados_bon)]
df_filtrado_dep = ddep[ddep['MES_ANO'].isin(mes_ano_selecionados_bon)]

df_agrupado_gasto = df_filtrado_gasto.groupby('MARCA')['VALOR_GASTO'].sum().reset_index()
df_agrupado_dep = df_filtrado_dep.groupby('MARCA')['VALOR_DEPOSITADO'].sum().reset_index()
df_agrupado_bon = df_filtrado_bon.groupby('MARCA')['VALOR_BONIFICADO'].sum().reset_index()

df_agrupado_cmv = cmv.groupby(['MARCA', 'ANO', 'MES']).agg({'ROB': 'sum', 'CUSTO': 'sum'}).reset_index()
df_agrupado_cmv['CMV'] = df_agrupado_cmv['CUSTO'] / df_agrupado_cmv['ROB']

df_completo = pd.merge(df_agrupado_gasto, df_agrupado_bon, on='MARCA', how='left')
df_completo = pd.merge(df_completo, df_agrupado_dep, on='MARCA', how='left')

df_cmv_filtrado = df_agrupado_cmv[df_agrupado_cmv['ANO'].isin(anos_selecionados_gasto) & df_agrupado_cmv['MES'].isin(meses_selecionados_gasto)]
df_completo_cmv = pd.merge(df_cmv_filtrado, df_completo, on='MARCA', how='left')

df_completo_cmv['CMV Ajustado'] = df_completo_cmv['CUSTO'] / (df_completo_cmv['ROB'] + df_completo_cmv['VALOR_GASTO'])

df_completo_cmv = df_completo_cmv.drop(columns=['ANO', 'MES', 'VALOR_GASTO', 'VALOR_BONIFICADO', 'VALOR_DEPOSITADO'])

df_completo = df_completo.fillna(0)
df_completo_cmv = df_completo_cmv.fillna(0)

marcas_filtradas = df_completo['MARCA'].unique()
df_completo_cmv = df_completo_cmv[df_completo_cmv['MARCA'].isin(marcas_filtradas)]

def formatar_moeda(valor):
    return locale.currency(valor, grouping=True)

df_completo['VALOR_GASTO'] = df_completo['VALOR_GASTO'].apply(formatar_moeda)
df_completo['VALOR_BONIFICADO'] = df_completo['VALOR_BONIFICADO'].apply(formatar_moeda)
df_completo['VALOR_DEPOSITADO'] = df_completo['VALOR_DEPOSITADO'].apply(formatar_moeda)

df_completo_cmv['ROB'] = df_completo_cmv['ROB'].apply(formatar_moeda)
df_completo_cmv['CUSTO'] = df_completo_cmv['CUSTO'].apply(formatar_moeda)

df_completo_cmv['CMV'] = df_completo_cmv['CMV'].apply(lambda x: f"{x*100:.2f}%")
df_completo_cmv['CMV Ajustado'] = df_completo_cmv['CMV Ajustado'].apply(lambda x: f"{x*100:.2f}%")

df_completo = df_completo.sort_values(by='VALOR_GASTO', ascending=False)
df_completo_cmv = df_completo_cmv.sort_values(by='ROB', ascending=False)

st.title("Painel")
st.write("### Gastos, Bonificação e CMV por Marca")

st.subheader("Gastos, Bonificação e Depósito")
st.dataframe(df_completo)

st.subheader("CMV e CMV Ajustado")
st.dataframe(df_completo_cmv)

if st.button('Exibir Bonificação'):
    st.subheader("Base de Dados de Bonificação")
    st.dataframe(dbon)

if st.button('Exibir Depósitos'):
    st.subheader("Base de Dados de Depósitos")
    st.dataframe(ddep)

def gerar_download_excel(df, nome_arquivo):
    output = BytesIO()
    with pd.ExcelWriter(output, engine='xlsxwriter') as writer:
        df.to_excel(writer, index=False, sheet_name="Dados")
    output.seek(0)
    return output

st.sidebar.subheader("Download de Bases")
btn_download_bon = st.sidebar.download_button(
    label="Baixar Bonificação",
    data=gerar_download_excel(dbon, "bonificacao.xlsx"),
    file_name="bonificacao.xlsx",
    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
)

btn_download_dep = st.sidebar.download_button(
    label="Baixar Depósitos",
    data=gerar_download_excel(ddep, "depositos.xlsx"),
    file_name="depositos.xlsx",
    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
)